export { default as Footer } from './Footer/Footer'
export { default as Cart } from './Cart'
export { default as Layout } from './Layout'
export { default as Navigation } from './Navbar'
export { default as HeroBanner } from './HeroBanner/HeroBanner'
export { default as Product } from './Product/Product'
export { default as HairTypes } from './HairTypes/HairTypes'
